import React from 'react';
import ReactDOM from 'react-dom/client';
import App from './App';
import './styles.css';
import './pages.css';
import './readability.css';
import './assistant.css';
import 'leaflet/dist/leaflet.css';
import './map.css';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
